# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
steps:
- checkout: self
# Compile application
- script: |
    javac Main.java
  displayName: 'Compile Java Code'

# Run tests
- script: |
    if [ -f ./test/TestRunner.class ]; then
      java -cp . test.TestRunner
    else
      echo "No tests to run."
    fi
  displayName: 'Run Java Tests'